### PR TITLE
Use specific version of gnostic for travis

### PR DESCRIPTION
**Pull request by LorenzHW**
Travis needs to use the same gnostic version as defined in go.mod. Otherwise local tests are green and Travis tests are red.

### CODE REVIEW

**Comment by skeid21** [comment]
Lorenz, 

Not sure how busy Tim is currently.  Would be good to get this before Raul's changes are ready to merge.   Change looks good to me, but if you want to wait for Tim we can.

**Comment by LorenzHW** [comment]
@skeid21 No we don't need to wait for Tim. I need at least one approved review though otherwise I can't merge it. Can you approve it?

Otherwise we can close this PR here and let Raul merge everything in his PR, because he already merged these commits into his branch.

**Review by skeid21 — APPROVED** [review]
lgtm

**Comment by skeid21** [comment]
Github develop is new to me.  Not sure educate on who kicks off the merge, so I went ahead and clicked the button :-D.   

Thanks for staying involved with the project!

**Comment by LorenzHW** [comment]
No worries. Someone has to press it :)

**Pull request merged**
