### PR TITLE
Fixing dead links + replacing "Parameters" suffix with "Request"

### LINKED ISSUE #21: Bind Parameters to Request suffix
Currently parameters are converted to an object with suffix Parameters.
Proposing if we can change this behaviour to

If its 1 parameter, pass it directly to rpc method args
Or add a Request suffix. Its seems more natural to understand.
```
"/pay/v1/transactions/{transactionId}/callback/pgs/payu": {
      "post": {
        "tags": [
          "callback-controller"
        ],
        "operationId": "payU",
        "parameters": [
          {
            "name": "transactionId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "default response"
          }
        }
      }
    }
```
creates
```
 rpc PayU ( PayUParameters ) returns ( google.protobuf.Empty ) {
    option (google.api.http) = { post:"/pay/v1/transactions/{transactionId}/callback/pgs/payu"  };
  }
```
Excepcted
```
 rpc PayU ( string ) returns ( google.protobuf.Empty ) {
    option (google.api.http) = { post:"/pay/v1/transactions/{transactionId}/callback/pgs/payu"  };
  }
```
OR
```
 rpc PayU ( PayURequest ) returns ( google.protobuf.Empty ) {
    option (google.api.http) = { post:"/pay/v1/transactions/{transactionId}/callback/pgs/payu"  };
  }
```

### LINKED ISSUE #27: Main README link to envoy is broken
implement that API using [gRPC-JSON Transcoding](https://www.envoyproxy.io/docs/envoy/latest/configuration/http_filters/grpc_json_transcoder_filter

### PR DESCRIPTION
**Pull request by LorenzHW**
Fixes #27 

Fixes #21

### CODE REVIEW

**Comment by noahdietz** [comment]
This seems fine, but what will this do to existing users? Their protos will change, thus all of their generated code based on those protos will change. Technically, this is a breaking change in the generated surface. We might want to consider creating a 0.x release with HEAD to capture the existing behavior, then merge this and make a 1.x release afterwards so that there is an easy way to pin installs to the "Parameters" behavior.

**Comment by LorenzHW** [comment]
Done. I created a tag with the name v0.1.0 in order to have the same naming convention as gnostic.

**Comment by noahdietz** [comment]
LGTM but I'd like @timburks to review it too. I'll let him approve it.

**Comment by LorenzHW** [comment]
friendly ping @timburks

**Comment by noahdietz** [comment]
FWIW we could do the README fix in a separate PR and merge that asap. They are unrelated changes.

**Review by timburks — APPROVED** [review]

**Comment by timburks** [comment]
Thanks! This is a good update for consistency with proto style recommendations (e.g. [AIP-131](https://google.aip.dev/131))

**Pull request merged**
